Repository kubernetes-sigs/kro, pull requests merged in 2025-09, with the labels that each got.

#661 feat(simpleschema): add support for pattern, minLength, maxLengt, uniqueItems, maxItems and minItems markers
  pkg/simpleschema/markers.go
  pkg/simpleschema/markers_test.go
  pkg/simpleschema/transform.go
  pkg/simpleschema/transform_test.go
  test/e2e/chainsaw/check-validation-markers/README.md
  test/e2e/chainsaw/check-validation-markers/chainsaw-test.yaml
  test/e2e/chainsaw/check-validation-markers/configmap-assert.yaml
  test/e2e/chainsaw/check-validation-markers/instancecrd-assert.yaml
  test/e2e/chainsaw/check-validation-markers/invalid-instance-array-limits.yaml
  test/e2e/chainsaw/check-validation-markers/invalid-instance-max-items.yaml
  test/e2e/chainsaw/check-validation-markers/invalid-instance-min-items.yaml
  test/e2e/chainsaw/check-validation-markers/invalid-instance-priorities-max.yaml
  test/e2e/chainsaw/check-validation-markers/invalid-length-error.yaml
  test/e2e/chainsaw/check-validation-markers/invalid-length-instance.yaml
  test/e2e/chainsaw/check-validation-markers/invalid-pattern-error.yaml
  test/e2e/chainsaw/check-validation-markers/invalid-pattern-instance.yaml
  test/e2e/chainsaw/check-validation-markers/invalid-unique-error.yaml
  test/e2e/chainsaw/check-validation-markers/invalid-unique-instance.yaml
  test/e2e/chainsaw/check-validation-markers/rgd-assert.yaml
  test/e2e/chainsaw/check-validation-markers/rgd.yaml
  test/e2e/chainsaw/check-validation-markers/valid-instance-assert.yaml
  test/e2e/chainsaw/check-validation-markers/valid-instance.yaml
  website/docs/docs/concepts/10-simple-schema.md
Labels: approved, lgtm, cncf-cla: yes, size/XXL

#676 Update NOTICE
  NOTICE
Labels: approved, lgtm, cncf-cla: yes, size/XS

#682 Mv hack under scripts to reduce Top level folders
  scripts/hack/toolchain.sh
Labels: approved, lgtm, cncf-cla: yes, size/XS

#687 CLA signed - removing from NOTICE
  NOTICE
Labels: approved, lgtm, cncf-cla: yes, size/XS

#689 Update(01-Installation.md):latest release version url
  website/docs/docs/getting-started/01-Installation.md
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/XS

#691 Add `self` and `this` to reserved keywords
  pkg/graph/validation.go
Labels: approved, lgtm, cncf-cla: yes, size/XS

#694 fix!: use kro-controller as leaderElectionID
  cmd/controller/main.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#651 docs: Update FAQ with instructions for using KRO with ArgoCD
  website/docs/docs/faq.md
  website/static/img/KRO-ArgoCD-Tracking.png
Labels: approved, lgtm, cncf-cla: yes, tide/merge-method-squash, ok-to-test, size/M

#616 fix!: properly shutdown controller manager and dynamic controller
  cmd/controller/main.go
  helm/templates/deployment.yaml
  helm/values.yaml
  pkg/dynamiccontroller/dynamic_controller.go
  pkg/dynamiccontroller/dynamic_controller_test.go
  test/integration/environment/setup.go
  test/integration/suites/ackekscluster/suite_test.go
  test/integration/suites/core/setup_test.go
  test/integration/suites/deploymentservice/suite_test.go
  test/integration/suites/networkingstack/suite_test.go
Labels: approved, lgtm, cncf-cla: yes, tide/merge-method-squash, size/L

#264 test(core): RGDs all the way down
  test/integration/suites/core/nested_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L

#701 Revert "test(core): RGDs all the way down"
  test/integration/suites/core/nested_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L
