Repository kubernetes-sigs/kro, pull requests merged in 2025-10, with the labels that each got.

#700 chore(tests): properly use SpecContext from Ginkgo
  Makefile
  test/integration/environment/setup.go
  test/integration/suites/ackekscluster/suite_test.go
  test/integration/suites/core/crd_test.go
  test/integration/suites/core/externalref_test.go
  test/integration/suites/core/garbage_collection_test.go
  test/integration/suites/core/include_when_test.go
  test/integration/suites/core/lifecycle_test.go
  test/integration/suites/core/nested_test.go
  test/integration/suites/core/readiness_test.go
  test/integration/suites/core/recover_test.go
  test/integration/suites/core/setup_test.go
  test/integration/suites/core/status_test.go
  test/integration/suites/core/topology_test.go
  test/integration/suites/core/validation_test.go
  test/integration/suites/deploymentservice/suite_test.go
  test/integration/suites/networkingstack/suite_test.go
Labels: approved, lgtm, cncf-cla: yes, size/XL

#705 !feat: Reserve item and items as keywords for collections
  pkg/graph/validation.go
Labels: approved, lgtm, cncf-cla: yes, size/XS

#706 chore: Tidy up lack of parity on dynamic controller interface
  pkg/controller/resourcegraphdefinition/controller_cleanup.go
  pkg/controller/resourcegraphdefinition/controller_reconcile.go
  pkg/dynamiccontroller/dynamic_controller.go
  pkg/dynamiccontroller/dynamic_controller_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#707 chore: Make dynamic controller logging object-type agnostic.
  pkg/dynamiccontroller/dynamic_controller.go
Labels: approved, lgtm, cncf-cla: yes, size/XS

#708 fix: Use controllerruntime's namespaced name correctly
  pkg/controller/instance/controller.go
  pkg/dynamiccontroller/dynamic_controller.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#710 chore: Hydrate goproxy after each push
  .github/workflows/postsubmit.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S
